SET FOREIGN_KEY_CHECKS = 0
DROP TABLE IF EXISTS `exp_skills`
DROP TABLE IF EXISTS `skills`
DROP TABLE IF EXISTS `experiences`
DROP TABLE IF EXISTS `positions`
DROP TABLE IF EXISTS `feedback`
DROP TABLE IF EXISTS `institutions`
DROP TABLE IF EXISTS `users`
SET FOREIGN_KEY_CHECKS = 1